[package]
name = "oo7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = "2.1"
serde = "1.0"
tokio = {version = "1.17", features = ["macros", "rt-multi-thread"]}
futures = "0.3"

[[bin]]
name = "basic"
path = "examples/basic.rs"

[dev-dependencies]
serde_json = "1.0"
