[package]
name = "oo7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = "2.1"
serde = "1.0"
tokio = {version = "1.17", features = ["macros", "rt-multi-thread"]}
futures = "0.3"
rand = {version = "0.8", default-features = false}

[features]
default = ["local_tests"]
# Some tests requires a prompt to be displayed, which can't be easily
# handled in CI unless we write a mock service. The feature allows to disabling those tests in CI
local_tests = []

[[bin]]
name = "basic"
path = "examples/basic.rs"

[dev-dependencies]
byteorder = "1.0"
