[package]
name = "oo7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = {version = "2.1", features = ["gvariant"]}
serde = "1.0"
futures = "0.3"
rand = {version = "0.8", default-features = false}
async-std = {version = "1.11", features = ["attributes"]}
byteorder = "1.0"
num = "0.4.0"

aes = "0.8"
cbc = "0.1"
cipher = {version = "0.4", features = ["rand_core"]}
digest = "0.10"
hmac = "0.12"
pbkdf2 = "0.11"
sha2 = "0.10"
zeroize = {version = "1.5", features = ["zeroize_derive"]}
hkdf = "0.12"

once_cell = "1.9"
dirs = "4.0"

[features]
default = ["local_tests"]
# Some tests requires a prompt to be displayed, which can't be easily
# handled in CI unless we write a mock service. The feature allows to disabling those tests in CI
local_tests = []

[[bin]]
name = "basic"
path = "examples/basic.rs"
