on:
  push:
    branches: [main]
  pull_request:

name: CI

jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Check (keyring-util)
        uses: actions-rs/cargo@v1
        with:
          working-directory: ./keyring-util
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get install gnome-keyring dbus dbus-x11 -y
          gnome-keyring-daemon -d
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build and test
        run: |
          dbus-run-session -- cargo test --no-default-features --features async-std --features native_crypto
      - name: Build and test (OpenSSL)
        run: |
          dbus-run-session -- cargo test --no-default-features --features async-std --features openssl_crypto
      - name: Build (keyring-util)
        working-directory: ./keyring-util
        run: |
          cargo build

  fmt:
    name: Rustfmt
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - name: Rust Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Rust Format (keyring-util)
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          working-directory: ./keyring-util
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
      - name: Clippy (keyring-util)
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          working-directory: ./keyring-util
          args: -- -D warnings
