on:
  push:
    branches: [master]
  pull_request:

name: Codespell

jobs:
  codespell:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          ignore_words_list: "crate,ser"
          check_hidden: false
          skip: "./.git/**"
          builtin: "clear,rare,informal,usage,code"
