name: github pages

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --package oo7 --all-features --no-deps

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        env:
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./target/doc/
